all:
  children:
    master:
      hosts:
        k8s-master:
          ansible_host: "{{ master_ip }}"

    workers:
      hosts:
        k8s-node-1:
          ansible_host: "{{ base_node_ip }}.{{ worker_ip_last[0] }}"

        k8s-node-2:
          ansible_host: "{{ base_node_ip }}.{{ worker_ip_last[1] }}"

    kubernetes:
      children:
        master:
        workers:
